name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: publish
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: "${{ secrets.GITHUBPAT }}"
          node-version: 12
          submodules: true

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: yarn install
        run: yarn install --prefer-offline --frozen-lockfile --no-progress --non-interactive

      - name: Get Outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short "$GITHUB_SHA")"

      - name: Publish
        run: |
          cp package.json build
          cp .npmrc build
          cd build
          npm publish

      - name: Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Published `rafflebox-prettier-config` to Github - <https://github.com/rafflebox-technologies-inc/rafflebox-prettier-config/commit/${{ steps.vars.outputs.sha_short }}|${{ steps.vars.outputs.sha_short }}>"}' https://hooks.slack.com/services/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

      - name: Failed
        if: ${{ failure() }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$GITHUB_WORKFLOW"' Failed for `${{ github.event.repository.name }}` - <'"$GITHUB_SERVER_URL"'/'"$GITHUB_REPOSITORY"'/actions/runs/'"$GITHUB_RUN_ID"'|View Run>"}' https://hooks.slack.com/services/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
